SRC=main.c sha256.c scrypt-nosse.c scryptenc.c crypto_aesctr.c
LIBS=-lcrypto -lrt

all: scrypt scrypt.so test

scrypt: $(SRC)
	gcc -o scrypt $(SRC) -DCONFIG_H_FILE=\"config_linux.h\" $(LIBS)

scrypt.so:
	gcc -shared -fPIC -o libscrypt.so -DCONFIG_H_FILE=\"config_linux.h\" $(SRC) $(LIBS)

test: scrypt.so
	gcc -o test test.c -I. -L. -lscrypt

clean:
	rm -f *.o *.so scrypt test
